<a href="https://colab.research.google.com/github/alyabdulfatah/NeuralNetwork/blob/master/anther_Simple_neural_network_backprop.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [0]:
class Neural_Network(object):
  def __init__(self):
  #parameters
    self.inputSize = 2    #future of student
    self.outputSize = 1   #score of exam
    self.hiddenSize = 3   #three neuron

  #weights
    self.W1 = np.random.randn(self.inputSize, self.hiddenSize) # (3x2) weight matrix from input to hidden layer
    #print(self.W1)
    self.W2 = np.random.randn(self.hiddenSize, self.outputSize) # (3x1) weight matrix from hidden to output layer
    #print(self.W2)


  def forward(self, X):
    #forward propagation through our network
    self.z = np.dot(X, self.W1) # dot product of X (input) and first set of 3x2 weights
    self.z2 = self.sigmoid(self.z) # activation function
    self.z3 = np.dot(self.z2, self.W2) # dot product of hidden layer (z2) and second set of 3x1 weights
    o = self.sigmoid(self.z3) # final activation function
    return o

  def sigmoid(self, s):
    # activation function
    return 1/(1+np.exp(-s))

  def sigmoidPrime(self, s):
    #derivative of sigmoid
    return s * (1 - s)

  def backward(self, X, y, o):
    # backward propagate through the network
    self.o_error = y - o # error in output
    self.o_delta = self.o_error*self.sigmoidPrime(o) # applying derivative of sigmoid to error

    self.z2_error = self.o_delta.dot(self.W2.T) # z2 error: how much our hidden layer weights contributed to output error
    self.z2_delta = self.z2_error*self.sigmoidPrime(self.z2) # applying derivative of sigmoid to z2 error

    self.W1 += X.T.dot(self.z2_delta) # adjusting first set (input --> hidden) weights
    self.W2 += self.z2.T.dot(self.o_delta) # adjusting second set (hidden --> output) weights

  def train(self, X, y):
    o = self.forward(X)
    self.backward(X, y, o)

  def saveWeights(self):
    np.savetxt("w1.txt", self.W1, fmt="%s")
    np.savetxt("w2.txt", self.W2, fmt="%s")

  def predict(self):
    print ("Predicted data based on trained weights: ")
    print ("Input (scaled): \n" + str(xPredicted))
    print ("Output: \n" + str(self.forward(xPredicted)))
   
  

In [0]:
# X = (hours studying, hours sleeping), y = score on test
xAll = np.array(([2, 9], [1, 5], [3, 6], [5, 10]), dtype=float) # input data
y = np.array(([92], [86], [89]), dtype=float) # output

In [0]:
# scale units
xAll = xAll/np.amax(xAll, axis=0) # scaling input data
y = y/100 # scaling output data (max test score is 100)

In [0]:
# split data
X = np.split(xAll, [3])[0] # training data
xPredicted = np.split(xAll, [3])[1] # testing data

y = np.array(([92], [86], [89]), dtype=float)
y = y/100 # max test score is 100


In [0]:
# scale units
#print(x)
x = x/np.amax(x, axis=0) # scaling input data
#print('__________')
#print(x)

#print(xpredicted)
xpredicted = xpredicted/np.amax(xpredicted, axis=0)
#print(xpredicted)


y = y/100 # scaling output data (max test score is 100)



In [125]:
NN = Neural_Network()
for i in range(1000): # trains the NN 1,000 times
  print ("# " + str(i) + "\n")
  print ("Input (scaled): \n" + str(X))
  print ("Actual Output: \n" + str(y))
  print ("Predicted Output: \n" + str(NN.forward(X)))
  print ("Loss: \n" + str(np.mean(np.square(y - NN.forward(X))))) # mean sum squared loss
  print ("\n")
  NN.train(X, y)

NN.saveWeights()
NN.predict()



Streaming output truncated to the last 5000 lines.
Predicted Output: 
[[0.0122776 ]
 [0.01964397]
 [0.01720835]]
Loss: 
6.68231419781737e-05


# 723

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.0092]
 [0.0086]
 [0.0089]]
Predicted Output: 
[[0.01227003]
 [0.01963355]
 [0.01719838]]
Loss: 
6.667580433998041e-05


# 724

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.0092]
 [0.0086]
 [0.0089]]
Predicted Output: 
[[0.01226249]
 [0.01962315]
 [0.01718844]]
Loss: 
6.652897092540934e-05


# 725

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.0092]
 [0.0086]
 [0.0089]]
Predicted Output: 
[[0.01225496]
 [0.01961277]
 [0.01717852]]
Loss: 
6.638263938768629e-05


# 726

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.0092]
 [0.0086]
 [0.0089]]
Predicted Output: 
[[0.01224744]
 [0.01960242]
 [0.01716863]]
Loss: 
6.623680739402937e-05


# 727

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual 

# New Section