In [0]:
import numpy as np

In [0]:
neuron = 4

In [0]:
def sigmoid (x):
  return 1.0/(1+np.exp(-x))

In [0]:
def sigmoid_derivative (x):
  return x*(1.0 - x)

In [0]:
class NeuralNetwork:
  def __init__(self, x, y):
    self.input      = x
    print('input \n',self.input)
    print( )
    self.weights1   = np.random.rand(self.input.shape[1],neuron) 
    print('weights1 \n',self.weights1)
    print( )
    self.weights2   = np.random.rand(neuron,1)
    print('weights2 \n',self.weights2)
    print( )                 
    self.y          = y
    print('y \n',self.y)
    print( )
    self.output     = np.zeros(self.y.shape) # y hat
    print('output \n',self.output)
    print( )
  def feedforward(self):
        self.layer1 = sigmoid(np.dot(self.input, self.weights1))
        print('layer \n',self.layer1)
        print( )
        self.output = sigmoid(np.dot(self.layer1, self.weights2))
        print('output \n',self.output)
        print( )

  def backprop(self):
        # application of the chain rule to find derivative of the loss function with respect to weights2 and weights1
        d_weights2 = np.dot(self.layer1.T, (2*(self.y - self.output) * sigmoid_derivative(self.output)))
        d_weights1 = np.dot(self.input.T,  (np.dot(2*(self.y - self.output) * sigmoid_derivative(self.output), self.weights2.T) * sigmoid_derivative(self.layer1)))

        # update the weights with the derivative (slope) of the loss function
        self.weights1 += d_weights1
        self.weights2 += d_weights2    
  

In [54]:
x = np.array([[0,0,1],
              [0,1,1],
              [1,0,1],
              [1,1,1]])
print(x)

[[0 0 1]
 [0 1 1]
 [1 0 1]
 [1 1 1]]


In [55]:
y = np.array([[0],
              [1],
              [1],
              [0]])
print(y)

[[0]
 [1]
 [1]
 [0]]


In [56]:
nn = NeuralNetwork(x,y)
'''
You must change the numbers from which you will benefit from this structure
This knowledge of trial and error to find the best way to work
'''
for i in range(10):
  nn.feedforward()
  nn.backprop()
  print("_____________________")
print (nn.output)  

input 
 [[0 0 1]
 [0 1 1]
 [1 0 1]
 [1 1 1]]

weights1 
 [[0.15199899 0.89793268 0.77596512 0.65947088]
 [0.00397101 0.00187216 0.12263184 0.19949077]
 [0.14641913 0.15592043 0.14967074 0.58558679]]

weights2 
 [[0.99348025]
 [0.63105804]
 [0.18829826]
 [0.97376424]]

y 
 [[0]
 [1]
 [1]
 [0]]

output 
 [[0.]
 [0.]
 [0.]
 [0.]]

layer 
 [[0.53653953 0.53890133 0.53734799 0.64235191]
 [0.53752683 0.5393665  0.5676581  0.68677341]
 [0.57405577 0.74151412 0.71618906 0.77644315]
 [0.57502645 0.74187279 0.74044211 0.80915801]]

output 
 [[0.83199049]
 [0.83889622]
 [0.87315877]
 [0.87726648]]

_____________________
layer 
 [[0.51516396 0.52668562 0.53370725 0.62691797]
 [0.50738366 0.52316204 0.5628758  0.66801557]
 [0.54330008 0.72816768 0.7120247  0.76039216]
 [0.53556425 0.7253619  0.73556544 0.79167255]]

output 
 [[0.74350569]
 [0.74751488]
 [0.77906508]
 [0.78155763]]

_____________________
layer 
 [[0.49627525 0.51799054 0.53436588 0.61408709]
 [0.47999442 0.51145261 0.56374895 0.6520