<a href="https://colab.research.google.com/github/alyabdulfatah/NeuralNetwork/blob/master/Simple_neural_network_backprop.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [0]:
neuron = 4

In [0]:
def sigmoid (x):
  return 1.0/(1+np.exp(-x))

In [0]:
def sigmoid_derivative (x):
  return x*(1.0 - x)

In [0]:
class NeuralNetwork:
  def __init__(self, x, y):
    self.input      = x
    print('input \n',self.input)
    print( )
    self.weights1   = np.random.rand(self.input.shape[1],neuron) 
    print('weights1 \n',self.weights1)
    print( )
    self.weights2   = np.random.rand(neuron,1)
    print('weights2 \n',self.weights2)
    print( )                 
    self.y          = y
    print('y \n',self.y)
    print( )
    self.output     = np.zeros(self.y.shape) # y hat
    print('output \n',self.output)
    print( )
  def feedforward(self):
        self.layer1 = sigmoid(np.dot(self.input, self.weights1))
        print('layer \n',self.layer1)
        print( )
        self.output = sigmoid(np.dot(self.layer1, self.weights2))
        print('output \n',self.output)
        print( )

  def backprop(self):
        # application of the chain rule to find derivative of the loss function with respect to weights2 and weights1
        d_weights2 = np.dot(self.layer1.T, (2*(self.y - self.output) * sigmoid_derivative(self.output)))
        print('d_weights2 \n',d_weights2)
        print( )
        d_weights1 = np.dot(self.input.T,  (np.dot(2*(self.y - self.output) * sigmoid_derivative(self.output), self.weights2.T) * sigmoid_derivative(self.layer1)))
        print('d_weights1 \n',d_weights1)
        print( )

        # update the weights with the derivative (slope) of the loss function
        self.weights1 += d_weights1
        self.weights2 += d_weights2    
  

In [66]:
x = np.array([[0,0,1],
              [0,1,1],
              [1,0,1],
              [1,1,1]])
print(x)

[[0 0 1]
 [0 1 1]
 [1 0 1]
 [1 1 1]]


In [67]:
y = np.array([[0],
              [1],
              [1],
              [0]])
print(y)

[[0]
 [1]
 [1]
 [0]]


In [68]:
nn = NeuralNetwork(x,y)
'''
You must change the numbers from which you will benefit from this structure
This knowledge of trial and error to find the best way to work
'''
for i in range(10):
  nn.feedforward()
  nn.backprop()
  print("_____________________")
print (nn.output)  

input 
 [[0 0 1]
 [0 1 1]
 [1 0 1]
 [1 1 1]]

weights1 
 [[0.11854008 0.89700331 0.54712089 0.22848407]
 [0.66883228 0.20953473 0.48303713 0.20901475]
 [0.75180846 0.67316796 0.60877028 0.75416963]]

weights2 
 [[0.63490587]
 [0.48543545]
 [0.74684751]
 [0.9203974 ]]

y 
 [[0]
 [1]
 [1]
 [0]]

output 
 [[0.]
 [0.]
 [0.]
 [0.]]

layer 
 [[0.67957263 0.66221215 0.64766024 0.68008656]
 [0.80543884 0.70738197 0.74872192 0.72375892]
 [0.70481822 0.82780802 0.76058532 0.72763445]
 [0.82334561 0.85566056 0.83738906 0.76703933]]

output 
 [[0.8655973 ]
 [0.88895322]
 [0.88964251]
 [0.90631916]]

d_weights2 
 [[-0.23065182]
 [-0.23161333]
 [-0.22642084]
 [-0.22338604]]

d_weights1 
 [[-0.01134976 -0.00772759 -0.01270436 -0.02135888]
 [-0.01203081 -0.00702405 -0.01257081 -0.02127715]
 [-0.03701327 -0.02739431 -0.04394882 -0.05765575]]

_____________________
layer 
 [[0.67145985 0.65605743 0.6375674  0.6674144 ]
 [0.79763799 0.70020712 0.73793976 0.70770246]
 [0.69465764 0.8227439  0.7501173  0.7