<a href="https://colab.research.google.com/github/alyabdulfatah/NeuralNetwork/blob/master/Simple_neural_network_backprop.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [0]:
neuron = 4

In [0]:
def sigmoid (x):
  return 1.0/(1+np.exp(-x))

In [0]:
def sigmoid_derivative (x):
  return x*(1.0 - x)

In [0]:
class NeuralNetwork:
  def __init__(self, x, y):
    self.input      = x
    #print('input \n',self.input) #for showing
    #print( )
    self.weights1   = np.random.rand(self.input.shape[1],neuron) 
    #print('weights1 \n',self.weights1) #for showing
    #print( )
    self.weights2   = np.random.rand(neuron,1)
    #print('weights2 \n',self.weights2) #for showing
    #print( )                 
    self.y          = y
    #print('y \n',self.y)
    #print( )
    self.output     = np.zeros(self.y.shape) # y hat
    #print('output \n',self.output) #for showing
    #print( )
  def feedforward(self):
        self.layer1 = sigmoid(np.dot(self.input, self.weights1))
        #print('layer \n',self.layer1) #for showing
        #print( )
        self.output = sigmoid(np.dot(self.layer1, self.weights2))
        #print('output \n',self.output) #for showing
        #print( )

  def backprop(self):
        # application of the chain rule to find derivative of the loss function with respect to weights2 and weights1
        d_weights2 = np.dot(self.layer1.T, (2*(self.y - self.output) * sigmoid_derivative(self.output)))
        #print('d_weights2 \n',d_weights2) #for showing
        #print( )
        d_weights1 = np.dot(self.input.T,  (np.dot(2*(self.y - self.output) * sigmoid_derivative(self.output), self.weights2.T) * sigmoid_derivative(self.layer1)))
        #print('d_weights1 \n',d_weights1) #for showing
        #print( )

        # update the weights with the derivative (slope) of the loss function
        self.weights1 += d_weights1
        self.weights2 += d_weights2    
  

In [74]:
x = np.array([[0,0,1],
              [0,1,1],
              [1,0,1],
              [1,1,1]])
print(x)

[[0 0 1]
 [0 1 1]
 [1 0 1]
 [1 1 1]]


In [75]:
y = np.array([[0],
              [1],
              [1],
              [0]])
print(y)

[[0]
 [1]
 [1]
 [0]]


In [77]:
nn = NeuralNetwork(x,y)
'''
You must change the numbers from which you will benefit from this structure
This knowledge of trial and error to find the best way to work
'''
for i in range(10):
  nn.feedforward()
  nn.backprop()
  #print("_____________________")
print (nn.output)  

[[0.5000235 ]
 [0.507778  ]
 [0.49425246]
 [0.50209311]]
